---
apiVersion: v1
kind: Namespace
metadata:
    name: supremo-rentals
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-svc
  labels:
    tier: frontend
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: react-frontend
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deploy
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: react-frontend
        tier: frontend
    spec:
      containers:
      - name: react-frontend
        image: bom.ocir.io/apaccpt01/frontend/react-supremo:${BUILDRUN_HASH}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "24Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # env:
        # - name: MDS_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mds-host-configmaps
        #       key: mds-host
        # - name: MDS_DATABASE
        #   valueFrom:
        #     secretKeyRef:
        #       name: mds-secret
        #       key: mds-database
        # - name: MDS_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: mds-secret
        #       key: mds-user
        # - name: MDS_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mds-secret
        #       key: mds-password
      imagePullSecrets:
      - name: ocir-secret