# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "OKE VCN Deployment"
description: "Terraform Script to deploy an OKE VCN"
informationalText: "Terraform Script to deploy an OKE VCN"
schemaVersion: 1.1.0
version: "20231026"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
    - compartment_ocid
    - tenancy_ocid
    - region

- title: General Configuration
  visible: true
  variables:
    - resource_naming_prefix

- title: Network Configuration
  visible: true
  variables:
    - oke_vcn_cidr_blocks
    - oke_k8sapiendpoint_subnet_cidr_block
    - oke_service_lb_subnet_cidr_block
    - oke_nodepool_cidr_block

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment OCID" 
    description: "Please select the target compartment"

  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: "Tenancy OCID"
    description: "Please select the target tenancy"

  region:
    type: oci:identity:region:name
    required: true
    title: "Region"
    description: "Please select the target region"

  resource_naming_prefix:
    type: string
    required: true
    title: "Resource naming prefix"
    description: "Please input the resource naming prefix for OCI resources"

  oke_vcn_cidr_blocks:
    type: string
    required: true
    title: "OKE VCN CIDR Block"
    description: "Please input the OKE VCN CIDR Block"

  oke_k8sapiendpoint_subnet_cidr_block:
    type: string
    required: true
    title: "OKE API Endpoint Subnet CIDR Block"
    description: "Please input the OKE API Endpoint Subnet CIDR Block"

  oke_service_lb_subnet_cidr_block:
    type: string
    required: true
    title: "OKE Service Load Balancer Subnet CIDR Block"
    description: "Please input the OKE Service Load Balancer Subnet CIDR Block"

  oke_nodepool_cidr_block:
    type: string
    required: true
    title: "OKE Node Pool Subnet CIDR Block"
    description: "Please input the OKE Node Pool Subnet CIDR Block"