apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: supremo-cert-prod
spec:
  commonName: supremo.oracledemo.online
  dnsNames:
    - supremo.oracledemo.online
  issuerRef:
    name: letsencrypt-prod
  secretName: supremo-cert-prod