---
apiVersion: v1
kind: Namespace
metadata:
    name: supremo-rentals-arm
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-svc
  labels:
    tier: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: supremorentalsarm.oracledemo.online
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: supremo-cert-prod
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  selector:
    app: react-frontend
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deploy
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: react-frontend
        tier: frontend
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: react-frontend
        image: bom.ocir.io/apaccpt01/frontend/react-supremo:${IMG_TAG}
        # image: bom.ocir.io/apaccpt01/frontend/react-supremo:multiarch.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "24Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: ocir-secret